version: '3'
services:
  db:
    image: postgres:11.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  web:
    image: odoo:13.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./volumes/odoo/config:/etc/odoo
      - ./volumes/odoo/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  reverse:
    container_name: reverse
    hostname: reverse
    depends_on:
      - web
    image: nginx:1.16.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/config/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/certs:/etc/ssl/private
volumes:
  odoo-web-data:
  odoo-db-data:
